platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target "Wrench" do
 pod "AFNetworking", "~> 3.0"
 pod 'SDWebImage', '~> 3.7.1'
 pod 'MJRefresh', '~> 3.0.2'
 pod 'Masonry', '~> 0.6.3'
 pod 'SVProgressHUD', '~> 1.1.3'
 pod 'MJExtension'
 pod 'IQKeyboardManager'
 pod 'pop', '~> 1.0'
 pod ‘UMengUShare/Social/Sina'
 pod ‘UMengUShare/Social/WeChat'
 pod ‘UMengUShare/Social/QQ'
 pod ‘UMengUShare/Social/AlipayShare'
 pod ‘UMengUShare/Social/SMS'
 pod 'UMengAnalytics-NO-IDFA'
end
